name: my first CI pipeline


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  test-job:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses : actions/checkout@v3


      - name: Say Hello
        run: echo "Hello CI"


      - name: Run a simple test script
        run: |
          echo "Running test..."
          echo "Test successful!"
          
