name: CI Pipeline


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  security-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


    # 1. Gitleaks ( secret scan )

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.30.0_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: clean workSpace
        run: |
          rm -rf .pytest_cache || true
          rm -rf __pycache__ || true

      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --no-git --exit-code 1
          
        

       



    # 2. Semgrep ( SAST )

      - name: Run semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"  # For production rulesets


    # 3. Trivy file system scan

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfl https://raw.githubusercontent.com/aquasecurity/trivy/refs/heads/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin   
          
          

      - name: Trivy file system scan ( Dependency + config )
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .


    # 4. Checkov ( Iac security scan )
      - name: Checkov - Terraform scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./Terraform
          soft_fail: true


  build-and-test:
    needs: security-tests
    runs-on: ubuntu-latest


    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
         cd app
         pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest -q

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u fruststorm --password-stdin

      - name: Build docker image
        run: |
          docker build -t ghcr.io/fruststorm/aegis-app:latest ./app
          

      # 5. Trivy Image scan

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ghcr.io/fruststorm/aegis-app:latest
          severity: CRITICAL,HIGH
          exit-code: 1


      - name: Push Docker image
        run: |
          docker push ghcr.io/fruststorm/aegis-app:latest
          echo "END..."
  
  
  dast-zap:
    name: DAST - OWASP ZAP
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application image
        run: docker build -t aegis-app:dast ./app

      - name: Run application container
        run: |
          docker run -d --name aegis-dast -p 5000:5000 aegis-app:dast
          
          echo "Waiting for app to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:5000/health; then
              echo "App is ready"
              break
            fi
            sleep 1
          done
      - name: Fix permission for ZAP
        run: |
          sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Run OWASP ZAP Baseline scan
        run: |
          docker run --rm --network host \
            -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:5000 \
          -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html

      
    
    






      
          
